### ISSUE TITLE
Change texture filtering mode of the quilt from point to bilinear

### ISSUE THREAD

**Issue by bburrough** [kirurobo/LookingGlassQuiltViewer#4]
Your quilts are rendering more pixelated than they could be. Simply change the texture filtering mode to bilinear or better and they will be more crisp and clear.

1) Open the project.
2) Hit play.
3) Select "HoloPlay Capture."
4) Look at the "Quilt" component in the inspector.
5) You should see that a quilt is set on the "Quilt RT" property. Double click it.
6) Notice the filtering mode. Is it point? If so, change it to bilinear.
7) Verify that the view is crisp and clean.

**Comment by kirurobo** [comment]
Thank you for your advice!

I added a code here.
https://github.com/kirurobo/LookingGlassQuiltViewer/blob/d5fa5701f23e0a84dd58a473f15cad8d38318c99/Assets/Scripts/QuiltFileLoader.cs#L236
Because in this project the texture will be recreated whenever the image loaded.

**Comment by bburrough** [comment]
お疲れ様です
